[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.28.1"
env_logger = "0.11.5"
interprocess = { version = "2.2.1", features = ["tokio"] }
tokio = { version = "1.39.3", features = ["full"] }
