[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
interprocess = "2.2.1"
log = "0.4.22"
serde_json = "1.0"
tokio = { version = "1.39.3", features = ["full"] }
handheld-shared = { path = "../handheld-shared" }
